# Setup
setup: single_task

# Database
train_db_name: NYUD
val_db_name: NYUD 
trBatch: 8
valBatch: 8
nworkers: 4

# Optimizer and scheduler
epochs: 100
optimizer: sgd
optimizer_kwargs:
   lr: 0.001
   momentum: 0.9
   weight_decay: 0.0001
scheduler: poly

# Model
model: baseline
backbone: VisionTransformer
backbone_kwargs:
   dilated: False
   model_name: 'vit_large_patch16_384'
   img_size: [480,640]
   patch_size: 16
   in_chans: 3
   embed_dim: 1024
   depth: 24
   num_heads: 16
   num_classes: 40
   mlp_ratio: 4.
   qkv_bias: True,
   drop_rate: 0.
   attn_drop_rate: 0.
   drop_path_rate: 0.
  #  norm_cfg: None
   pos_embed_interp: True
   random_init: False
   align_corners: False
head: VisionTransformerUpHead
head_kwargs:
   img_size: [480,640]
   patch_size: 16
   embed_dim: 1024
   # norm_cfg: None
   conv3x3_conv1x1: True
   in_channels: 1024
   channels: 512
   in_index: 23
   align_corners: False
   num_conv: 4
   upsampling_method: 'bilinear'
   num_upsampe_layer: 4
   num_classes: 40

# Tasks
task_dictionary:
   include_semseg: True


# Eval only final 10 epochs for speed-up
# eval_final_10_epochs_only: True


